kind: Namespace
apiVersion: v1
metadata:
  name: argotunnel
  labels:
    name: argotunnel

---

kind: Namespace
apiVersion: v1
metadata:
  name: jenkins
  labels:
    name: jenkins

---

kind: Namespace
apiVersion: v1
metadata:
  name: db
  labels:
    name: db

